<a href="https://colab.research.google.com/github/darshilnagle7-create/pandas-assignments/blob/main/pandas_class6_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [4]:
# Write your code here
import pandas as pd

a = {
    'City':["Bhopal", "Indore", "Bhopal", "Delhi"]
}
b = pd.DataFrame(a)
b
b['City'].unique()

array(['Bhopal', 'Indore', 'Delhi'], dtype=object)


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [7]:
# Write your code here
b
b['City'].nunique()

3


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [9]:
# Write your code here
b['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [16]:
# Write your code here
a = {
    'City':["Bhopal", "Indore", "Bhopal", "Delhi"],
    'Marks':[80,90,70,60]
}
b = pd.DataFrame(a)
b
city_marks = b.groupby('City')['Marks'].mean()
print(city_marks)

City
Bhopal    75.0
Delhi     60.0
Indore    90.0
Name: Marks, dtype: float64


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [18]:
# Write your code here
a = {
    'City':["Bhopal", "Indore", "Bhopal", "Delhi"],
    'Marks':[80,90,70,60],
    'Name':['Kunal','Himanshu','Raj','Tony']
}
b = pd.DataFrame(a)
b
b.sort_values(by='Marks')

     City  Marks      Name
3   Delhi     60      Tony
2  Bhopal     70       Raj
0  Bhopal     80     Kunal
1  Indore     90  Himanshu


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [22]:
# Write your code here
b.sort_values(by='Marks',ascending=False)

     City  Marks      Name
1  Indore     90  Himanshu
0  Bhopal     80     Kunal
2  Bhopal     70       Raj
3   Delhi     60      Tony


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [24]:
# Write your code here
b[b['Marks'] > 75]

     City  Marks      Name
0  Bhopal     80     Kunal
1  Indore     90  Himanshu


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [29]:
# Write your code here
a = {
    'City':["Bhopal", "Indore", "Bhopal", "Delhi"],
    'Marks':[80,90,70,60],
    'Name':['Kunal','Himanshu','Raj','Tony'],
    'Age':[20,24,22,35]
}
b = pd.DataFrame(a)
b
b[(b['Marks'] > 70) &( b['Age'] > 20)]

     City  Marks      Name  Age
1  Indore     90  Himanshu   24


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [31]:
# Write your code here
a = {
    "Employee": ["Aman", "Riya", "Rohit", "Priya"],
    "Department": ["HR", "IT", "HR", "IT"],
    "Salary": [20000, 50000, 30000, 70000]
}
b = pd.DataFrame(a)
b
b.groupby('Department')['Salary'].sum()

Department
HR     50000
IT    120000
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [39]:
# Write your code here
a = {
    "Name": ["Aman", "Riya", "Rohit", "Priya"],
    "Age": [20, 21, 22, 20],
    "City": ["Bhopal", "Indore", "Bhopal", "Delhi"],
    "Marks": [85, 92, 78, 88]
}
b = pd.DataFrame(a)
b
b['City'].unique()
b['City'].value_counts()
b[b['Marks'] > 80]
b.sort_values(by = 'Marks')

    Name  Age    City  Marks
2  Rohit   22  Bhopal     78
0   Aman   20  Bhopal     85
3  Priya   20   Delhi     88
1   Riya   21  Indore     92