<a href="https://colab.research.google.com/github/darshilnagle7-create/pandas-assignments/blob/main/Pandas_class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [ ]:
avg_salary = df.groupby('Department')['Salary'].mean() # har department ki average salary

count_people = df.groupby('Department')['Employee'].count() # har department me kitne ke log hai
print(count_people)

multi_stats = df.groupby('Department')['Salary'].agg(['mean','min','max',])
print(multi_stats)

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64
                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.groupby('Department')['Age'].mean()

#df.groupby('Department).agg{column:ispe lagana kya }
df.groupby('Department').agg(
    {'Salary':['mean','min','max'],
     'Age':['min','max']
     }
)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

                  Salary               Age
                    mean    min    max min max
Department
Finance     61000.000000  58000  65000  26  35
HR          51000.000000  50000  52000  28  29
IT          72333.333333  70000  75000  30  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
# df.pivot_table(index ='konsa column main hai',values = 'kya chiye',aggfunction=mean,min,max)

df.pivot_table(index = 'Department', values = 'Salary', aggfunc='mean')

df.pivot_table(index = 'Department', values = [ 'Salary','Age'], aggfunc='mean')


#Age Group -> 21-25,25-30,31-35
df['Age_Group'] = pd.cut(df['Age'],bins=[25,30,35,40],labels=["25-30","31-35","36-40"])

pd.crosstab(df['Department'],df['Age_Group'])
df

  Employee Department  Salary  Age Age_Group
0     John         HR   50000   28     25-30
1    Sarah         IT   70000   32     31-35
2     Mike         IT   72000   30     25-30
3     Anna    Finance   65000   27     25-30
4      Tom    Finance   60000   35     31-35
5    Laura         HR   52000   29     25-30
6    Steve         IT   75000   31     31-35
7     Kate    Finance   58000   26     25-30

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [9]:
from numpy import mean

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
import pandas as pd
a = {
    'Department':['HR','IT','FINANCE','SALES','IT','HR','FINANCE','SALES','SALES','HR'],
    'Employee':['Himanshu','Raj','Kunal','Gulshan','Shivan','Bhavesh','David','Priyanshu','Chetan','Sagar'],
    'Salary':[25000,45000,16000,13000,53000,19000,23000,26000,85000,90000],
    'Age':[25,30,32,26,34,23,20,31,39,40],
    'City':['Bhopal','Indore','Jabalpur','Ujjan','Dewas','Vidhisha','Jaipur','Manali','Mumbai','Pune'],

}
b = pd.DataFrame(a)
b

# 2. Group by Department to get average Salary and max Age
# Write your code here
b.groupby('Department').agg(
    {'Salary':[mean],
     'Age':[max]
    }
)

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here


# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
b.pivot_table(index='Department',values=['Salary'],columns=['City'],aggfunc='mean')

# 5. Build a crosstab for Department vs City
# Write your code here
pd.crosstab(b['Department'],b['City'])

/tmp/ipykernel_561/703445851.py:18: FutureWarning: The provided callable <function mean at 0x7c129213e3e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  b.groupby('Department').agg(
/tmp/ipykernel_561/703445851.py:18: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  b.groupby('Department').agg(

City,Bhopal,Dewas,Indore,Jabalpur,Jaipur,Manali,Mumbai,Pune,Ujjan,Vidhisha
Department,,,,,,,,,,
FINANCE,0,0,0,1,1,0,0,0,0,0
HR,1,0,0,0,0,0,0,1,0,1
IT,0,1,1,0,0,0,0,0,0,0
SALES,0,0,0,0,0,1,1,0,1,0

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.