<a href="https://colab.research.google.com/github/darshilnagle7-create/pandas-assignments/blob/main/pandas_class4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 4 Assignment


# Q1. Select Single Column

## Problem Statement
Create a DataFrame and display only the Name column.

## Sample Input
```python
Name, Age
```

## Sample Output
```python
Only Name column
```

In [7]:
# Write your code here
import pandas as pd
a = {
    'Name':['Darshil','Bhavesh','Kunal','Harshit'],
    'Age':[20,23,24,26],

}
b = pd.DataFrame(a)
b
b['Name']

0    Darshil
1    Bhavesh
2      Kunal
3    Harshit
Name: Name, dtype: object


# Q2. Select Multiple Columns

## Problem Statement
Display Name and Marks columns from a DataFrame.

## Sample Input
```python
Name, Marks
```

## Sample Output
```python
Selected columns
```

In [8]:
# Write your code here
a = {
    'Name':['Darshil','Bhavesh','Kunal','Harshit'],
    'Age':[20,23,24,26],
    'Marks':[60,70,80,90]

}
b = pd.DataFrame(a)
b
b[['Name','Marks']]

      Name  Marks
0  Darshil     60
1  Bhavesh     70
2    Kunal     80
3  Harshit     90


# Q3. Filter Students

## Problem Statement
Display students with Marks greater than 80.

## Sample Input
```python
Marks > 80
```

## Sample Output
```python
Filtered rows
```

In [8]:
# Write your code here
b[(b['Marks'] > 80)]

      Name  Age  Marks
3  Harshit   26     90


# Q4. Filter by City

## Problem Statement
Display students belonging to Bhopal.

## Sample Input
```python
City = Bhopal
```

## Sample Output
```python
Matching rows
```

In [9]:
# Write your code here
a = {
    'Name':['Darshil','Bhavesh','Kunal','Harshit'],
    'Age':[20,23,24,26],
    'City':['Bhopal','Indore','Balaghat','Betul']

}
b = pd.DataFrame(a)
b

b[(b['City'] == 'Bhopal')]

      Name  Age    City
0  Darshil   20  Bhopal


# Q5. Find Maximum Marks

## Problem Statement
Find the highest marks from a DataFrame.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Highest value
```

In [10]:
# Write your code here
a = {
    'Name':['Darshil','Bhavesh','Kunal','Harshit'],
    'Age':[20,23,24,26],
    'City':['Bhopal','Indore','Balaghat','Betul'],
    'Marks':[80,30,90,15]
}
b = pd.DataFrame(a)
b['Marks'].max()

90


# Q6. Find Minimum Age

## Problem Statement
Find the minimum age.

## Sample Input
```python
Age column
```

## Sample Output
```python
Minimum age
```

In [11]:
# Write your code here
print(b)
b['Age'].min()

      Name  Age      City  Marks
0  Darshil   20    Bhopal     80
1  Bhavesh   23    Indore     30
2    Kunal   24  Balaghat     90
3  Harshit   26     Betul     15

20


# Q7. Sort Data

## Problem Statement
Sort students by Marks.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Sorted DataFrame
```

In [12]:
# Write your code here
print(b)
b.sort_values(by='Marks')

      Name  Age      City  Marks
0  Darshil   20    Bhopal     80
1  Bhavesh   23    Indore     30
2    Kunal   24  Balaghat     90
3  Harshit   26     Betul     15

      Name  Age      City  Marks
3  Harshit   26     Betul     15
1  Bhavesh   23    Indore     30
0  Darshil   20    Bhopal     80
2    Kunal   24  Balaghat     90


# Q8. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City column
```

## Sample Output
```python
Frequency count
```

In [15]:
# Write your code here

print(b['City'].value_counts())

City
Bhopal      1
Indore      1
Balaghat    1
Betul       1
Name: count, dtype: int64


# Q9. Group By City

## Problem Statement
Find average marks city-wise.

## Sample Input
```python
City and Marks
```

## Sample Output
```python
Grouped result
```

In [17]:
# Write your code here
b.groupby('City')['Marks'].mean()

City
Balaghat    90.0
Betul       15.0
Bhopal      80.0
Indore      30.0
Name: Marks, dtype: float64


# Q10. Multiple Conditions

## Problem Statement
Display students with Marks > 70 and Age > 20.

## Sample Input
```python
Marks and Age
```

## Sample Output
```python
Filtered rows
```

In [19]:
# Write your code here
b[(b['Marks'] > 70) & (b['Age'] > 20)]

    Name  Age      City  Marks
2  Kunal   24  Balaghat     90